FROM teslamint/openwrt-builder:latest

USER build
WORKDIR /home/build/openwrt

ADD conf/config.iptime_a604m .config

RUN make oldconfig && \
    make -j$(nproc) tools/install && \
    make -j$(nproc) toolchain/install && \
    rm -rf dl tmp

ENTRYPOINT [ "make", "-j$(nproc)" ]
