FROM teslamint/openwrt-builder:latest

USER build
WORKDIR /home/build/openwrt

ADD conf/config.iptime_a604m .config

RUN make oldconfig && \
    make tools/install && \
    make -j1 toolchain/install

ENTRYPOINT [ "make" ]
