FROM teslamint/openwrt-builder:latest-base

USER build
WORKDIR /home/build/openwrt

ADD conf/config.w2914nsv2 .config

RUN make oldconfig && \
    make -j$(nproc) tools/install && \
    make -j$(nproc) toolchain/install && \
    rm -rf dl tmp

ENTRYPOINT [ "make", "-j$(nproc)" ]
