FROM teslamint/openwrt-builder:latest-base

USER build
WORKDIR /home/build/openwrt

ADD conf/config.iptime_a604m .config
ADD run-make.sh run-make.sh

RUN make oldconfig && \
    make -j$(nproc) tools/install && \
    make -j$(nproc) toolchain/install && \
    rm -rf dl tmp

ENTRYPOINT [ "./run-make.sh" ]
