version: 2.1
jobs:
  build:
    docker:
      - image: docker.io/openwrtorg/packages-cci:v1.0.5
    environment:
      - SDK_HOST: "downloads.openwrt.org"
      - SDK_PATH: "snapshots/targets/ramips/mt76x8"
      - SDK_FILE: "openwrt-sdk-ramips-mt76x8_*.Linux-x86_64.tar.xz"
      - BRANCH: "master"
    steps:
      - checkout:
          path: ~/builder

      - run:
          name: Download the SDK
          working_directory: ~/sdk
          command: |
             curl "https://$SDK_HOST/$SDK_PATH/sha256sums" -sS -o sha256sums
             curl "https://$SDK_HOST/$SDK_PATH/sha256sums.asc" -fs -o sha256sums.asc || true
             curl "https://$SDK_HOST/$SDK_PATH/sha256sums.sig" -fs -o sha256sums.sig || true
             if [ ! -f sha256sums.asc ] && [ ! -f sha256sums.sig ]; then
                 echo_red "Missing sha256sums signature files"
                 exit 1
             fi
             [ ! -f sha256sums.asc ] || gpg --with-fingerprint --verify sha256sums.asc sha256sums
             if [ -f sha256sums.sig ]; then
                 VERIFIED=
                 for KEY in ~/usign/*; do
                     echo "Trying $KEY..."
                     if signify-openbsd -V -q -p "$KEY" -x sha256sums.sig -m sha256sums; then
                         echo "...verified"
                         VERIFIED=1
                         break
                     fi
                 done
                 if [ -z "$VERIFIED" ]; then
                     echo_red "Could not verify usign signature"
                     exit 1
                 fi
             fi
             rsync -av "$SDK_HOST::downloads/$SDK_PATH/$SDK_FILE" .
             sha256sum -c --ignore-missing sha256sums
      - run:
          name: Prepare build_dir
          working_directory: ~/build_dir
          command: |
             tar Jxf ~/sdk/$SDK_FILE --strip=1
             cp -v ~/builder/conf/config.iptime_a604m .config
             echo 'src-git base https://github.com/openwrt/openwrt' > feeds.conf
             cat ~/builder/conf/feeds.conf | tee -a feeds.conf
             cat feeds.conf
             ./scripts/feeds update -a > /dev/null
             git clone https://github.com/stangri/openwrt_packages ~/openwrt_packages
             cp -Rfv ~/openwrt_packages/vpn-policy-routing feeds/packages/net/
             cp -Rfv ~/openwrt_packages/luci-app-vpn-policy-routing feeds/luci/applications/
             scripts/feeds update packages > /dev/null
             scripts/feeds update luci > /dev/null
             make oldconfig > /dev/null
             # enable BUILD_LOG
             sed -i 's/# CONFIG_BUILD_LOG is not set/CONFIG_BUILD_LOG=y/' .config
      - run:
          name: Install & download source, check package, compile
          working_directory: ~/build_dir
          command: |
             set +o pipefail
             ./scripts/feeds install -a
             make
      - store_artifacts:
          path: ~/build_dir/logs
      - store_artifacts:
          path: ~/build_dir/bin
workflows:
  version: 2
  buildpr:
    jobs:
      - build